version: '3'

services:
  oaza:
    build:
      dockerfile: build/dev/Dockerfile
    container_name: oaza
    ports:
      - 443:443
    volumes:
      - .:/app/
    env_file:
      - ./build/dev/oaza.env
    networks:
      - database_default
networks:
  database_default:
    external: true