<!DOCTYPE html><!-- "' --></script></style></noscript></xmp>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<link href="../www/bower/bootstrap/dist/css/bootstrap.css" rel="stylesheet"/>
<link href="../www/assets/css/style.css" rel="stylesheet"/>
<link rel="shortcut icon" href="/images/palm.png">

<title>Server Error</title>

<div class="row" style="margin-top: 30vh; height: 55vh">
    <div class="col-md-4 col-md-offset-4" style="text-align: center">
        <h1 class="custom-color-text">Server Error</h1>

        <p>We're sorry! The server encountered an internal error and
            was unable to complete your request. Please try again later.</p>

        <p><small>error 500</small></p>
    </div>
</div>
<style>
    body {
        background-color: white;
    }
</style>